name: gametime
description: gametime

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  redux: 3.0.0
  flutter_redux: 0.5.0
  side_header_list_view:
  share:
  url_launcher:
  google_sign_in:
  firebase_auth:
  cloud_firestore: 0.3.0
  image_carousel:
  scoped_model: 0.2.0

  flutter_speed_dialer:
    path: ../flutter_speed_dialer

  local_notifications: 0.0.6
  igdb_client:
    path: ../igdb_client


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  assets:
    - assets/img/placeholder.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: CaviarDreams
      fonts:
        - asset: assets/fonts/CaviarDreams.ttf
          weight: 400
    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 600
    - family: NanumPenScript
      fonts:
        - asset: assets/fonts/NanumPenScript-Regular.ttf
          weight: 600

  # To add assets to your application, add an assets section here, in
  # this "flutter" section, as in:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # To add assets from package dependencies, first ensure the asset
  # is in the lib/ directory of the dependency. Then,
  # refer to the asset with a path prefixed with
  # `packages/PACKAGE_NAME/`. Note: the `lib/` is implied, do not
  # include `lib/` in the asset path.
  #
  # Here is an example:
  #
  # assets:
  #  - packages/PACKAGE_NAME/path/to/asset

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
